# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 06fefda2135bfdc21299c46f1189234e6f8bb0d1cf642007f7c8a9f01f718670aa4712bd80b33ab495b02de46c0f1f1cd942f5cb0bc4138efa0c2eb8ee6e3c4e

test:
  secret_key_base: 60c7c2ff0b7dc066b773b411b85d77f611b437a5258ce6af6789bf3c0d2dec4f57d19e2566f75a848ad518d15523d861995a3cce3d3e87d38b30bc4e00c908c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
